name: Build

on:
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

permissions:
  contents: write
  actions: write
  pull-requests: write

run-name: Build from ${{ github.ref }}

jobs:
  formatting-tests:
    name: Consistency and formatting
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python: [ "3.9", "3.10", "3.11", "pypy3.9", "pypy3.10" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Formatting tests
        run: |
          poetry install --with dev
          poetry run black --check .
          poetry run isort --check .
          poetry run autoflake --check .


  unit-tests:
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python: [ "3.9", "3.10", "pypy3.9", "pypy3.10" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Unit tests
        run: |
          poetry install
          poetry run pytest -v src/tests/
